"""Centralized language code mappings used across the package."""

# ISO 639-1 → full language name (used by Whisper API, report generation, etc.)
LANG_CODE_TO_NAME: dict[str, str] = {
    "af": "afrikaans",
    "ar": "arabic",
    "bn": "bengali",
    "cs": "czech",
    "da": "danish",
    "de": "german",
    "el": "greek",
    "en": "english",
    "es": "spanish",
    "fi": "finnish",
    "fr": "french",
    "he": "hebrew",
    "hi": "hindi",
    "hu": "hungarian",
    "id": "indonesian",
    "it": "italian",
    "ja": "japanese",
    "ko": "korean",
    "mr": "marathi",
    "ms": "malay",
    "nl": "dutch",
    "no": "norwegian",
    "pl": "polish",
    "pt": "portuguese",
    "ro": "romanian",
    "ru": "russian",
    "sv": "swedish",
    "sw": "swahili",
    "ta": "tamil",
    "te": "telugu",
    "th": "thai",
    "tr": "turkish",
    "uk": "ukrainian",
    "ur": "urdu",
    "vi": "vietnamese",
    "zh": "chinese",
}

# ISO 639-1 → ISO 639-3 (used by ElevenLabs API)
LANG_CODE_TO_ELEVENLABS: dict[str, str] = {
    "af": "afr",
    "ar": "arb",
    "bn": "ben",
    "cs": "ces",
    "da": "dan",
    "de": "deu",
    "el": "ell",
    "en": "eng",
    "es": "spa",
    "fi": "fin",
    "fr": "fra",
    "he": "heb",
    "hi": "hin",
    "hu": "hun",
    "id": "ind",
    "it": "ita",
    "ja": "jpn",
    "ko": "kor",
    "mr": "mar",
    "ms": "msa",
    "nl": "nld",
    "no": "nob",
    "pl": "pol",
    "pt": "por",
    "ro": "ron",
    "ru": "rus",
    "sv": "swe",
    "sw": "swa",
    "ta": "tam",
    "te": "tel",
    "th": "tha",
    "tr": "tur",
    "uk": "ukr",
    "ur": "urd",
    "vi": "vie",
    "zh": "cmn",
}


def to_long_name(code: str) -> str:
    """Convert a language code to its full name, falling back to the code itself."""
    return LANG_CODE_TO_NAME.get(code.lower(), code.lower())
